services:
    proxy:
        container_name: kip-proxy
        restart: always
        image: ghcr.io/geeksaider/kip-proxy:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./data:/data/caddy
