name: "Build docker image and deploy"
on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
     
   steps: 
   - name: Checkout code
     uses: actions/checkout@v4
     
   - name: Login to GitHub container registry
     uses: docker/login-action@v3
     with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      
   - name: Docker create buildx
     run: docker buildx create --use 
     
   - name: Create docker image
     run: docker buildx build -t ghcr.io/geeksaider/kip-proxy --push .
   
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
  #       with:
  #         bundler-cache: true
  #     - name: Run command on remote server
  #       uses: D3rHase/ssh-command-action@v0.2.2
  #       with:
  #         host: ${{secrets.SSH_HOST}}
  #         user: ${{secrets.SSH_USER}}
  #         private_key: ${{secrets.SSH_PRIVATE_KEY}}
  #         command: |
  #           cd ${{ secrets.PROJECT_FOLDER }};
            # git checkout main;
            # git pull;
            # docker-compose --file docker-compose.prod.yml down;
            # docker-compose --file docker-compose.prod.yml up -d;
            # docker system prune --all --force;
