name: "Build docker image and deploy"
on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
     
   steps: 
   - name: Checkout code
     uses: actions/checkout@v4
     
   - name: Login to GitHub container registry
     uses: docker/login-action@v3
     with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      
   - name: Docker create buildx
     run: docker buildx create --use 
     
   - name: Create docker image
     run: docker buildx build -t ghcr.io/geeksaider/kip-proxy --push .
   
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: copy docker compose config
        run: scp docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:kip
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd kip && docker compose pull && docker compose up -d && exit"
     
